language: node_js
node_js:
  - 8
cache:
  yarn: true
  directories:
    - ~/.cache
install:
  - yarn install --frozen-lockfile

before_script:
  - yarn start &
  - sleep 10
script:
  - curl localhost:3000
  - cypress run --record
