language: node_js
node_js:
  - 8
cache:
  yarn: true
  directories:
    - ~/.cache
    - node_modules
install:
  - yarn
before_script:
  - yarn build:prod
  - serve -s dist &
script:
  - cypress run --record

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./deploy.sh
    on:
      branch: master
