language: node_js
node_js:
  - 8
addons:
  apt:
    packages:
      - sshpass
  ssh_known_hosts: snutt.kr
cache:
  yarn: true
  directories:
    - ~/.cache
    - node_modules
install:
  - yarn
before_script:
  - yarn build
  - serve -s build &
script:
  - cypress run --record

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./deploy.sh
    on:
      branch: master
