language: node_js
node_js:
  - 8
cache:
  yarn: true
  directories:
    - ~/.cache
    - node_modules
install:
  - yarn
before_script:
  - yarn build:prod
  - serve -s dist &
script:
  - cypress run --record
