export const LOAD_OK = 'loading/LOAD_OK';
export const LOGIN_OK = 'user/LOGIN_OK';

export const UPDATE_NEW_MESSAGE_COUNT = 'noti/UPDATE_NEW_MESSAGE_COUNT';

export const HOVER_COURSE = 'HOVER_COURSE';
export const UNHOVER_COURSE = 'UNHOVER_COURSE';

export const TABLE_HOVER_COURSE = 'TABLE_HOVER_COURSE';
export const TABLE_UNHOVER_COURSE = 'TABLE_UNHOVER_COURSE';

export const SET_LEFT_TAB = 'SET_LEFT_TAB';

export const ADD_QUERY = 'ADD_QUERY';
export const UPDATE_QUERY = 'UPDATE_QUERY';
export const REMOVE_QUERY = 'REMOVE_QUERY';
export const RESET_QUERY = 'RESET_QUERY';

export const SEND_QUERY = 'SEND_QUERY';
export const START_QUERY = 'START_QUERY';
export const SHOW_RESULT = 'SHOW_RESULT';

export const CREATE_COURSE = 'CREATE_COURSE';
export const ADD_COURSE = 'ADD_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const EDIT_COURSE = 'EDIT_COURSE';
export const CLOSE_COURSE = 'CLOSE_COURSE';

export const FETCH_COURSEBOOK = 'FETCH_COURSEBOOK';
export const CHANGE_COURSEBOOK = 'CHANGE_COURSEBOOK';

export const TOGGLE_SEARCHPANEL = 'TOGGLE_SEARCHPANEL';
export const TOGGLE_TIMEPANEL = 'TOGGLE_TIMEPANEL';
export const TOGGLE_USETIME = 'TOGGLE_USETIME';
export const SELECT_TIMEMODE = 'SELECT_TIMEMODE';

export const REQUEST_TABLELIST = 'REQUEST_TABLELIST';
export const GET_TABLELIST = 'GET_TABLELIST';
export const FAIL_TABLELIST = 'FAIL_TABLELIST';

export const REQUEST_TAG = 'REQUEST_TAG';
export const GET_TAG = 'GET_TAG';
export const FAIL_TAG = 'FAIL_TAG';

export const ADD_LECTURE_START = 'ADD_LECTURE_START';
export const ADD_LECTURE_OK = 'ADD_LECTURE_OK';
export const ADD_LECTURE_FAIL = 'ADD_LECTURE_FAIL';

export const DELETE_LECTURE_START = 'DELETE_LECTURE_START';
export const DELETE_LECTURE_OK = 'DELETE_LECTURE_OK';
export const DELETE_LECTURE_FAIL = 'DELETE_LECTURE_FAIL';

export const UPDATE_LECTURE_START = 'UPDATE_LECTURE_START';
export const UPDATE_LECTURE_OK = 'UPDATE_LECTURE_OK';
export const UPDATE_LECTURE_FAIL = 'UPDATE_LECTURE_FAIL';

export const UPDATE_TITLE_START = 'UPDATE_TITLE_START';
export const UPDATE_TITLE_OK = 'UPDATE_TITLE_OK';
export const UPDATE_TITLE_FAIL = 'UPDATE_TITLE_FAIL';

export const CREATE_TABLE_START = 'CREATE_TABLE_START';
export const CREATE_TABLE_OK = 'CREATE_TABLE_OK';
export const CREATE_TABLE_FAIL = 'CREATE_TABLE_FAIL';

export const DELETE_TABLE_START = 'DELETE_TABLE_START';
export const DELETE_TABLE_OK = 'DELETE_TABLE_OK';
export const DELETE_TABLE_FAIL = 'DELETE_TABLE_FAIL';

export const SWITCH_TABLE_START = 'SWITCH_TABLE_START';
export const SWITCH_TABLE_OK = 'SWITCH_TABLE_OK';
export const SWITCH_TABLE_FAIL = 'SWITCH_TABLE_FAIL';

export const GET_COLOR_START = 'GET_COLOR_START';
export const GET_COLOR_OK = 'GET_COLOR_OK';
export const GET_COLOR_FAIL = 'GET_COLOR_FAIL';

export const ADD_TIMETABLE = 'ADD_TIMETABLE';
export const CHANGE_TIMETABLE = 'CHANGE_TIMETABLE';
export const DELETE_TIMETABLE = 'DELETE_TIMETABLE';

export const FETCH_TAG = 'FETCH_TAG';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
