export const HOVER_COURSE = 'HOVER_COURSE'
export const UNHOVER_COURSE = 'UNHOVER_COURSE'

export const ADD_QUERY = 'ADD_QUERY'
export const UPDATE_QUERY = 'UPDATE_QUERY'
export const REMOVE_QUERY = 'REMOVE_QUERY'
export const RESET_QUERY = 'RESET_QUERY'

export const SEND_QUERY = 'SEND_QUERY'
export const START_QUERY = 'START_QUERY'
export const SHOW_RESULT = 'SHOW_RESULT'

export const ADD_COURSE = 'ADD_COURSE'
export const DELETE_COURSE = 'DELETE_COURSE'
export const OPEN_COURSE = 'OPEN_COURSE'
export const MODIFY_COURSE = 'MODIFY_COURSE'

export const CHANGE_TIMETABLE = 'CHANGE_TIMETABLE'
export const ADD_TIMETABLE = 'ADD_TIMETABLE'
export const DELETE_TIMETABLE = 'DELETE_TIMETABLE'

export const FETCH_COURSEBOOK = 'FETCH_COURSEBOOK'
export const CHANGE_COURSEBOOK = 'CHANGE_COURSEBOOK'

export const TOGGLE_SEARCHPANEL = 'TOGGLE_SEARCHPANEL'
export const TOGGLE_TIMESELECT = 'TOGGLE_TIMESELECT'

export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const SET_LEFT_TAB = 'SET_LEFT_TAB'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const REQUEST_TABLELIST = 'REQUEST_TABLELIST'
export const GET_TABLELIST = 'GET_TABLELIST'
export const FAIL_TABLELIST = 'FAIL_TABLELIST'

export const REQUEST_TAG = 'REQUEST_TAG'
export const GET_TAG = 'GET_TAG'
export const FAIL_TAG = 'FAIL_TAG'

export const ADD_LECTURE_START ='ADD_LECTURE_START'
export const ADD_LECTURE_OK = 'ADD_LECTURE_OK'
export const ADD_LECTURE_FAIL = 'ADD_LECTURE_FAIL'
