export const HOVER_COURSE = 'HOVER_COURSE'
export const UNHOVER_COURSE = 'UNHOVER_COURSE'

export const ADD_QUERY = 'ADD_QUERY'
export const UPDATE_QUERY = 'UPDATE_QUERY'
export const REMOVE_QUERY = 'REMOVE_QUERY'
export const RESET_QUERY = 'RESET_QUERY'
export const SEND_QUERY = 'SEND_QUERY'
export const START_QUERY = 'START_QUERY'
export const SHOW_RESULT = 'SHOW_RESULT'

export const ADD_COURSE = 'ADD_COURSE'
export const DELETE_COURSE = 'DELETE_COURSE'
export const OPEN_COURSE = 'OPEN_COURSE'
export const MODIFY_COURSE = 'MODIFY_COURSE'

export const CHANGE_TIMETABLE = 'CHANGE_TIMETABLE'
export const ADD_TIMETABLE = 'ADD_TIMETABLE'
export const DELETE_TIMETABLE = 'DELETE_TIMETABLE'

export const CHANGE_COURSEBOOK = 'CHANGE_COURSEBOOK'

export const TOGGLE_SEARCHPANEL = 'TOGGLE_SEARCHPANEL'
export const TOGGLE_TIMESELECT = 'TOGGLE_TIMESELECT'

export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const SET_LEFT_TAB = 'SET_LEFT_TAB'
